json.extract! driving_school,
              :id,
              :name,
              :phone_number,
              :email,
              :website_link,
              :additional_information,
              :city,
              :street,
              :zip_code,
              :country,
              :profile_picture,
              :status,
              :latitude,
              :longitude,
              :time_zone
