json.extract! custom_activity_type,
              :id,
              :title,
              :subtitle,
              :message_template,
              :target_type,
              :notification_receivers,
              :datetime_input_config,
              :text_note_input_config,
              :btn_bg_color,
              :datetime_input_instructions,
              :text_note_input_instructions
