json.extract! relationship,
              :id,
              :verb,
              :subject_type,
              :subject_id,
              :object_type,
              :object_id,
              :object_label,
              :subject_label,
              :voice
